### ISSUE TITLE
TypeError: vars() argument must have __dict__ attribute

### ISSUE THREAD

**Issue by cnicodeme** [sanic-org/tracerite#6]
When having an exception, the call to `vars(value).items()` fails with an exception in inspector.py at line 42:

> Traceback (most recent call last):
>   File "/home/cx42/www/getfernand.com/api/env/lib64/python3.10/site-packages/tracerite/inspector.py", line 42, in extract_variables
>     for n, v in vars(value).items():
> TypeError: vars() argument must have __dict__ attribute

**Comment by Tronic** [comment]
I presume this was on an object that has `__slots__` (there are many of those in Sanic). That case at least is fixed as soon as we get that PR released.

**Comment by Tronic** [comment]
Can you try the PR to see if it resolves the issue?

```fish
pip install "git+https://github.com/sanic-org/tracerite.git@inspector-vars#egg=tracerite"
```
